/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_equipo14;

import Paquete_Captcha.Captcha;
import java.awt.Image;
/**
 *
 * Mendez Garcia Angel de Jesus y Perez Jimenez Santiago Enmanuel
 */
public class Prueba_Equipo14 extends javax.swing.JFrame 
{

    /**
     * Creates new form Prueba_Equipo14
     */
    Image ImagenCaptcha; 
    String CaptchaGenerado;

    /**
     *
     */
    public Prueba_Equipo14() 
    {
        initComponents();
        lblResultado.setVisible(false);
        Captcha.Restricciones_TxT(txtCaptcha, 2);
        Captcha.Restricciones_TxT(txtCaptchaLongitud, 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Opciones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rdbtSoloNumeros = new javax.swing.JRadioButton();
        rdbtSoloLetras = new javax.swing.JRadioButton();
        rdbtCombinado = new javax.swing.JRadioButton();
        lblImagen = new javax.swing.JLabel();
        txtCaptchaLongitud = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCaptcha = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setBackground(new java.awt.Color(44, 62, 80));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione un tipo de Captcha");
        jLabel1.setOpaque(true);

        rdbtSoloNumeros.setBackground(new java.awt.Color(189, 195, 199));
        Opciones.add(rdbtSoloNumeros);
        rdbtSoloNumeros.setText("Solo Numeros");

        rdbtSoloLetras.setBackground(new java.awt.Color(189, 195, 199));
        Opciones.add(rdbtSoloLetras);
        rdbtSoloLetras.setText("Solo Letras");

        rdbtCombinado.setBackground(new java.awt.Color(189, 195, 199));
        Opciones.add(rdbtCombinado);
        rdbtCombinado.setText("Combinado");

        txtCaptchaLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaptchaLongitudActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(189, 195, 199));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingresa la longitud del Captcha");
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(189, 195, 199));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Ingresa el Captcha");
        jLabel4.setOpaque(true);

        btnAceptar.setBackground(new java.awt.Color(52, 152, 219));
        btnAceptar.setFont(new java.awt.Font("Segoe UI Variable", 0, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Verificar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        lblResultado.setBackground(new java.awt.Color(189, 195, 199));
        lblResultado.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(102, 0, 0));
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCaptcha, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(txtCaptchaLongitud))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbtSoloNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdbtSoloLetras, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdbtCombinado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(rdbtSoloNumeros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbtSoloLetras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbtCombinado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCaptchaLongitud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAceptar)
                .addGap(18, 18, 18)
                .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if(!Captcha.ValidarCaptcha(txtCaptcha.getText(), CaptchaGenerado, lblResultado))
        {
            if(rdbtSoloNumeros.isSelected())
            {
                CaptchaGenerado = Captcha.GenerarCaptchaSoloNumeros( Integer.parseInt(txtCaptchaLongitud.getText()));
                ImagenCaptcha = Captcha.CrearImagen(CaptchaGenerado);
            }
            if(rdbtSoloLetras.isSelected())
            {
                CaptchaGenerado = Captcha.GenerarCaptchaSoloLetras( Integer.parseInt(txtCaptchaLongitud.getText()));
                ImagenCaptcha = Captcha.CrearImagen(CaptchaGenerado);
            }
            if(rdbtCombinado.isSelected())
            {
                CaptchaGenerado =Captcha.GenerarCaptchaCombinados( Integer.parseInt(txtCaptchaLongitud.getText()));
                ImagenCaptcha = Captcha.CrearImagen(CaptchaGenerado);
            }
            if (txtCaptcha.getText().isEmpty() && txtCaptchaLongitud.getText().isEmpty())
            {
                lblResultado.setVisible(true);
                lblResultado.setText("Por favor rellena los campos requeridos");
            }
            else
            {
                Captcha.AgregarImagen(ImagenCaptcha, lblImagen);
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtCaptchaLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaptchaLongitudActionPerformed
        // TODO add your handling code here:
        if (!txtCaptchaLongitud.getText().isEmpty())
        {
            if(rdbtSoloNumeros.isSelected())
            {
                CaptchaGenerado = Captcha.GenerarCaptchaSoloNumeros( Integer.parseInt(txtCaptchaLongitud.getText()));
                ImagenCaptcha = Captcha.CrearImagen(CaptchaGenerado);
            }
            if(rdbtSoloLetras.isSelected())
            {
                CaptchaGenerado = Captcha.GenerarCaptchaSoloLetras( Integer.parseInt(txtCaptchaLongitud.getText()));
                ImagenCaptcha = Captcha.CrearImagen(CaptchaGenerado);
            }
            if(rdbtCombinado.isSelected())
            {
                CaptchaGenerado =Captcha.GenerarCaptchaCombinados( Integer.parseInt(txtCaptchaLongitud.getText()));
                ImagenCaptcha = Captcha.CrearImagen(CaptchaGenerado);
            }
            if(!rdbtSoloNumeros.isSelected() && !rdbtSoloLetras.isSelected() && !rdbtCombinado.isSelected())
            {
                lblResultado.setVisible(true);
                lblResultado.setText("Por favor seleciona una opcion de Captcha");
            }
            Captcha.AgregarImagen(ImagenCaptcha, lblImagen);
        }
        if (txtCaptchaLongitud.getText().isEmpty())
        {
            lblResultado.setVisible(true);
            lblResultado.setText("Por favor ingresa una longitud al Captcha");
        }
    }//GEN-LAST:event_txtCaptchaLongitudActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prueba_Equipo14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prueba_Equipo14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prueba_Equipo14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prueba_Equipo14.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new Prueba_Equipo14().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Opciones;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton rdbtCombinado;
    private javax.swing.JRadioButton rdbtSoloLetras;
    private javax.swing.JRadioButton rdbtSoloNumeros;
    private javax.swing.JTextField txtCaptcha;
    private javax.swing.JTextField txtCaptchaLongitud;
    // End of variables declaration//GEN-END:variables
}
